server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/tds_users_brinquedos
    username: postgres

